---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: current
  label: current
- type: file
  name: cover
  label: cover
- type: boolean
  name: navigation
  label: navigation
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: boolean
  name: frontpagepost
  label: frontpagepost
- type: text
  name: class
  label: class
- type: text
  name: subclass
  label: subclass
- type: text
  name: author
  label: author
pages:
- _posts/2022-01-07-airplane-task-scheduling.md
